# Generated by Django 5.1.2 on 2024-11-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_userprofile_nav_body_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='nav_body_images',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='nav_hover_images',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nav_body_images1',
            field=models.ImageField(blank=True, null=True, upload_to='nav_body_images1/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nav_body_images2',
            field=models.ImageField(blank=True, null=True, upload_to='nav_body_images2/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nav_body_images3',
            field=models.ImageField(blank=True, null=True, upload_to='nav_body_images3/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nav_hover_images1',
            field=models.ImageField(blank=True, null=True, upload_to='nav_hover_images1/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nav_hover_images2',
            field=models.ImageField(blank=True, null=True, upload_to='nav_hover_images2/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nav_hover_images3',
            field=models.ImageField(blank=True, null=True, upload_to='nav_hover_images3/'),
        ),
    ]
