# Generated by Django 5.1.2 on 2024-11-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_remove_userprofile_nav_body_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
