# Generated by Django 5.1.2 on 2024-11-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_about_title_about_title_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='work_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_heading',
            field=models.TextField(blank=True, null=True),
        ),
    ]
